geforce3090.constraint = "geforce3090"
geforce3090.partition = ""
geforce3090.account = ""
geforce3090.nodelist = ""
geforce3090.reservation = ""

v100.constraint = "v100"
v100.partition = ""
v100.account = ""
v100.nodelist = ""
v100.reservation = ""

a6000.constraint = "a6000"
a6000.partition = ""
a6000.account = ""
a6000.nodelist = ""
a6000.reservation = ""

a40.constraint = "a40"
a40.partition = ""
a40.account = ""
a40.nodelist = ""
a40.reservation = ""

l40.constraint = "l40"
l40.partition = ""
l40.account = ""
l40.nodelist = ""
l40.reservation = ""

a100.constraint = "a100"
a100.partition = ""
a100.account = ""
a100.nodelist = ""
a100.reservation = ""

h100.constraint = "h100"
h100.partition = ""
h100.account = ""
h100.nodelist = ""
h100.reservation = ""
